In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

## The NumPy ndarray - allows you to run mathematical calculations on a block of data

In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [4]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

In [8]:
## Creating arrays using the array function

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
## Nested sequences will be converted into a multidimensional array

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [13]:
arr2 = np.array(data2)

In [14]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

In [17]:
## np.array tries to infer a good data type for the array it creates

In [18]:
arr1.dtype

dtype('float64')

In [19]:
arr2.dtype

dtype('int64')

In [20]:
## create an array of 0s or 1s using .zeroes or .ones

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.empty((2, 3, 2))

array([[[ 0.00000000e+000,  3.11109895e+231],
        [ 2.96439388e-323, -2.68679749e+154],
        [ 4.95515891e-062,  8.78010386e-071]],

       [[ 4.91415367e-062,  5.49723877e+170],
        [ 1.90228430e-052,  4.50503864e-033],
        [ 4.08404176e+179,  8.34402697e-309]]])

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
## Data types for ndarrays

In [26]:
## dtype is a special object containing the metadata about the array 

In [27]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
arr = np.array([1, 2, 3, 4, 5]) 

In [31]:
arr.dtype

dtype('int64')

In [32]:
float_arr = arr.astype(np.float64)

In [33]:
float_arr

array([1., 2., 3., 4., 5.])

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [39]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [40]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
## using another arrays dtype to change array dtype

In [41]:
int_array = np.arange(10)

In [42]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [ ]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [45]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [ ]:
## Arithmetic with Nump