In [60]:
import pandas as pd

# 5.1 Introduction to pandas Data Structures

### Series

In [61]:
obj = pd.Series([4, 7, -5, 3])

In [62]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [63]:
obj.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [64]:
obj.index

RangeIndex(start=0, stop=4, step=1)

## Setting the index values to values other than n - 1

In [65]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [66]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [67]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [68]:
obj2["a"]

-5

In [69]:
obj2["d"] = 6

In [70]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [71]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [72]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [73]:
import numpy as np

In [74]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [75]:
"b" in obj2

True

In [76]:
"e" in obj2

False

## Declare a dict

In [77]:
 sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

## Convert dict to Series

In [78]:
obj3 = pd.Series(sdata)

In [79]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

## Convert Series to dict

In [80]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [81]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [82]:
obj4 = pd.Series(sdata, index=states)

In [83]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

## Check for NA values in obj4

In [84]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

## Check for values not NA in obj4

In [85]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [86]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [87]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [88]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [89]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

## Setting the name attribute of the object and index

In [90]:
obj4.name = "population"
obj4.index.name = "state"

In [91]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [92]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

## Altering a Series' index by in place assigment

In [93]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

In [94]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## Creating a DataFrame from a dictionary of equal length lists

In [95]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [96]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

## Selecting first five rows using head method

In [97]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

## Selecting last five rows using tail method

In [98]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

## Changing sequence of columns

In [100]:
pd.DataFrame(data, columns=["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

## Passing a non-existent column with return a column with NA values

In [102]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [103]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [104]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

## Retrieving particular columns using dictionary notation

In [105]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

## Retrieving particular columns using dot attribute notation

In [107]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

## Retrieving row by label indexing

In [109]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

## Retrieving row by integer indexing

In [110]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

## Modifying column by scalar assignment

In [111]:
frame2["debt"] = 16.5

In [112]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

## Modifying column by array of values

In [115]:
frame2["debt"] = np.arange(6.)

In [116]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [118]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [119]:
frame2["debt"] = val

In [120]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [124]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [125]:
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [126]:
del frame2["eastern"]

In [127]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [128]:
In [72]: populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9}}

In [129]:
frame3 = pd.DataFrame(populations)

## Converting nested dict to DataFrame, outer dict keys=columns, inner dict keys=row indices

In [130]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

## Transposing rows and columns

In [132]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [133]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [134]:
pdata = {"Ohio": frame3["Ohio"][:-1], "Nevada": frame3["Nevada"][:2]}

In [135]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [136]:
frame3.index.name = "year"
frame3.columns.name = "state"

In [137]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

## Return data in DataFrame as 2D numpy array

In [139]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

## If columns in DF are different data types, data type of array will accomodate all of the columns

In [140]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [141]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index = obj.index

In [142]:
index

Index(['a', 'b', 'c'], dtype='object')

In [143]:
index[1:]

Index(['b', 'c'], dtype='object')

In [145]:
# index[1] = "d" # Type Error

In [146]:
labels = pd.Index(np.arange(3))

In [147]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [148]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [149]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [150]:
obj2.index is labels

True

In [151]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [152]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [153]:
"Ohio" in frame3.columns

True

In [154]:
2003 in frame3.columns

False

## pandas Index can contain duplicate labels

In [156]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [157]:
obj

a    0
b    1
c    2
dtype: int64

In [158]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [159]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

## Using reindex to rearrange data according to new index

In [162]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [163]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [165]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [166]:
obj3

0      blue
2    purple
4    yellow
dtype: object

## Forward fill index values

In [167]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [169]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=["a", "c", "d"], columns=["Ohio", "Texas", "California"])

In [170]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [171]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])

In [172]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

## Columns can be reindexed with the columns keyword

In [174]:
states = ["Texas", "Utah", "California"]

In [175]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## Reindexing using the axis keyword

In [176]:
frame.reindex(states, axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [177]:
## Reindexing using loc

In [178]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

In [179]:
## Dropping Entries from and Axis

In [182]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [183]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [184]:
new_obj = obj.drop("c")

In [185]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [186]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [187]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
   .....:                     index=["Ohio", "Colorado", "Utah", "New York"],
   .....:                     columns=["one", "two", "three", "four"])

In [188]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

# Calling drop on sequence of labels will drop values from the row labels

In [189]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

# Drop labels from columns using columns keyword

In [191]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

## Dropping values from columns using axis keyword

In [193]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [194]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## Indexing, Selection, and Filtering

In [199]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [200]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [201]:
obj["b"]

1.0

In [202]:
obj[1]

1.0

In [203]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [205]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [206]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [209]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

## Selecting index values using the loc operator

In [211]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [212]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [213]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [214]:
obj1

2    1
0    2
1    3
dtype: int64

In [215]:
obj2

a    1
b    2
c    3
dtype: int64

In [216]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [217]:
obj2[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

## Using the iloc operator

In [220]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [221]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

## Slicing with labels is inclusive

In [223]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [224]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
   .....:                     index=["Ohio", "Colorado", "Utah", "New York"],
   .....:                     columns=["one", "two", "three", "four"])

In [225]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [226]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [227]:
data[["three", "one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [228]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [229]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## Comparing a DataFrame with a scalar value

In [230]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

## Assigning 0 to each location with True

In [232]:
data[data < 5] = 0

In [233]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## Selection on DataFrame with loc and iloc

In [235]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [236]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [237]:
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [239]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [240]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [241]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [242]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [243]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [244]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [245]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [246]:
ser = pd.Series(np.arange(3.))

In [247]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

## ser[-1] cannot access last element the way you can in lists or tuples

In [249]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [250]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])

In [251]:
ser2[-1]

2.0

In [252]:
ser.iloc[-1]

2.0

In [253]:
data.loc[:, "one"] = 1

In [254]:
data.iloc[2] = 5

In [256]:
data.loc[data["four"] > 5] = 3

In [257]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [258]:
data.loc[data.three == 5, "three"] = 6

In [259]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

In [260]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [261]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [262]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [263]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [264]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
   .....:                    index=["Ohio", "Texas", "Colorado"])

In [265]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
   .....:                    index=["Utah", "Ohio", "Texas", "Oregon"])

In [266]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [267]:
df1 = pd.DataFrame({"A": [1, 2]})

In [268]:
df2 = pd.DataFrame({"B": [3, 4]})

In [269]:
df1

A
0  1
1  2

In [270]:
df2

B
0  3
1  4

In [271]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [272]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
   .....:                    columns=list("abcd"))

In [273]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
   .....:                    columns=list("abcde"))

In [274]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [275]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [276]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [277]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [278]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

## The r reverses the arguments

In [281]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

## When reindexing a Series or DataFram you can also specify a different fill value

In [282]:
arr = np.arange(12.).reshape((3, 4))

In [283]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [284]:
arr[0]

array([0., 1., 2., 3.])

In [286]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [287]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
   .....:                      columns=list("bde"),
   .....:                      index=["Utah", "Ohio", "Texas", "Oregon"])

In [290]:
series = frame.iloc[0]

In [289]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [291]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [292]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [294]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [295]:
series2

b    0
e    1
f    2
dtype: int64

In [296]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [297]:
series3 = frame["d"]

In [298]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [299]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [300]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [301]:
## Function Application and Mapping

In [302]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
   .....:                      columns=list("bde"),
   .....:                      index=["Utah", "Ohio", "Texas", "Oregon"])

In [303]:
frame

b         d         e
Utah    0.095635 -0.176846  0.184028
Ohio    0.194843  1.598779  0.666253
Texas   0.928057 -0.381522  1.338289
Oregon  0.240687  0.376983  0.991866

In [304]:
np.abs(frame)

b         d         e
Utah    0.095635  0.176846  0.184028
Ohio    0.194843  1.598779  0.666253
Texas   0.928057  0.381522  1.338289
Oregon  0.240687  0.376983  0.991866

In [307]:
def f1(x):
    return x.max() - x.min()

In [ ]:
## Use apply method to use function on DataFrame

In [308]:
frame.apply(f1)

b    0.832422
d    1.980301
e    1.154261
dtype: float64

In [310]:
frame.apply(f1, axis="columns")

Utah      0.360874
Ohio      1.403936
Texas     1.719811
Oregon    0.751178
dtype: float64

In [313]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [314]:
frame.apply(f2)

b         d         e
min  0.095635 -0.381522  0.184028
max  0.928057  1.598779  1.338289

In [315]:
def my_format(x):
    return f"{x: .2f}"

In [316]:
frame.applymap(my_format)

b      d      e
Utah     0.10  -0.18   0.18
Ohio     0.19   1.60   0.67
Texas    0.93  -0.38   1.34
Oregon   0.24   0.38   0.99

In [317]:
frame["e"].map(my_format)

Utah       0.18
Ohio       0.67
Texas      1.34
Oregon     0.99
Name: e, dtype: object

## Sorting and Ranking: To sort lexicographically by row or column label, use the sort_index method, which returns a new, sorted object

In [319]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [320]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [321]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [322]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
   .....:                      index=["three", "one"],
   .....:                      columns=["d", "a", "b", "c"])

In [323]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [324]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [326]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [327]:
frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [328]:
obj = pd.Series([4, 6, -3, 2])

In [329]:
obj.sort_values()

2   -3
3    2
0    4
1    6
dtype: int64

In [ ]:
## Sort missing values first using na_position option

In [330]:
obj.sort_values(na_position="first")

2   -3
3    2
0    4
1    6
dtype: int64

In [331]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [332]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [333]:
frame.sort_values("b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [334]:
frame.sort_values(["a", "b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

## Using the rank method which breaks ties by assigning each group the mean rank

In [335]:
obj = pd.Series([7, -5, 4, 2, 0, 4])

In [336]:
obj.rank()

0    6.0
1    1.0
2    4.5
3    3.0
4    2.0
5    4.5
dtype: float64

In [337]:
obj.rank(method="first")

0    6.0
1    1.0
2    4.0
3    3.0
4    2.0
5    5.0
dtype: float64

In [338]:
obj.rank(ascending=False)

0    1.0
1    6.0
2    2.5
3    4.0
4    5.0
5    2.5
dtype: float64

In [339]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
   .....:                       "c": [-2, 5, 8, -2.5]})

In [340]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [341]:
frame.rank(axis="columns")

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [342]:
## Axis Indexes with Duplicate Labels

In [343]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [344]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [345]:
## is_unique property of the index can tell you whether or not its labels are unique

In [347]:
obj.index.is_unique

False

In [348]:
obj["a"]

a    0
a    1
dtype: int64

In [349]:
obj["c"]

4

In [350]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
   .....:                   index=["a", "a", "b", "b", "c"])

In [351]:
df

0         1         2
a  0.030426  1.641010  0.558190
a  0.106964 -0.637489  1.717898
b -0.175508 -1.224369  1.088387
b  0.090249 -1.062678 -0.613569
c  1.706918 -1.831853 -1.626446

In [352]:
df.loc["b"]

0         1         2
b -0.175508 -1.224369  1.088387
b  0.090249 -1.062678 -0.613569

In [353]:
df.loc["c"]

0    1.706918
1   -1.831853
2   -1.626446
Name: c, dtype: float64

In [354]:
## Summarizing and Computing Descriptive Statistics

In [355]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
   .....:                    [np.nan, np.nan], [0.75, -1.3]],
   .....:                   index=["a", "b", "c", "d"],
   .....:                   columns=["one", "two"])

In [356]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [357]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [358]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [359]:
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [360]:
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [361]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [362]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [363]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [365]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [366]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [373]:
## Correlation and Covariance

In [370]:
# price = pd.read_pickle("examples/yahoo_price.pkl")

In [372]:
# volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [374]:
# returns = price.pct_change()

In [375]:
# returns.tail()

In [376]:
# returns["MSFT"].corr(returns["IBM"])

In [377]:
# returns["MSFT"].cov(returns["IBM"])

In [378]:
# returns["MSFT"].corr(returns["IBM"])

In [379]:
# returns.corr()

In [380]:
# returns.cov()

In [381]:
# returns.corrwith(returns["IBM"])

In [382]:
# returns.corrwith(volume)

In [383]:
## Unique Values, Value Counts, and Membership

In [384]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [385]:
uniques = obj.unique()

In [386]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [387]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [388]:
pd.value_counts(obj.to_numpy(), sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [389]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [390]:
mask = obj.isin(["b", "c"])

In [391]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [392]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [393]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])

In [394]:
unique_vals = pd.Series(["c", "b", "a"])

In [395]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [396]:
indices

array([0, 2, 1, 1, 0, 2])

In [397]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
   .....:                      "Qu2": [2, 3, 1, 2, 3],
   .....:                      "Qu3": [1, 5, 2, 4, 4]})

In [398]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [399]:
data["Qu1"].value_counts().sort_index()

1    1
3    2
4    2
Name: Qu1, dtype: int64

In [400]:
result = data.apply(pd.value_counts).fillna(0)

In [402]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [403]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})

In [404]:
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [405]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
dtype: int64