In [12]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [13]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

## The NumPy ndarray - allows you to run mathematical calculations on a block of data

In [14]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [15]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [16]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [17]:
data.shape

(2, 3)

In [18]:
data.dtype

dtype('float64')

## Creating arrays using the array function

In [19]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [20]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

## Nested sequences will be converted into a multidimensional array

In [21]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [22]:
arr2 = np.array(data2)

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

## np.array tries to infer a good data type for the array it creates

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int64')

## create an array of 0s or 1s using .zeroes or .ones

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.empty((2, 3, 2))

array([[[1.49166815e-154, 1.49166815e-154],
        [4.44659081e-323, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data types for ndarrays

## dtype is a special object containing the metadata about the array 

In [32]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [33]:
arr1.dtype

dtype('float64')

In [34]:
arr2.dtype

dtype('int32')

In [35]:
arr = np.array([1, 2, 3, 4, 5]) 

In [36]:
arr.dtype

dtype('int64')

In [37]:
float_arr = arr.astype(np.float64)

In [38]:
float_arr

array([1., 2., 3., 4., 5.])

In [39]:
float_arr.dtype

dtype('float64')

In [40]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [41]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [42]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [43]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [44]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## using another arrays dtype to change array dtype

In [45]:
int_array = np.arange(10)

In [46]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [47]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [49]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## Arithmetic with Numpy Arrays

In [50]:
arr = np.array([[1., 2., 3.], [4., 5., 6]])

In [51]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [52]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [53]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
1 - arr

array([[ 0., -1., -2.],
       [-3., -4., -5.]])

In [55]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [56]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [57]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [58]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [59]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [60]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [61]:
## Basic Indexing and Slicing

In [62]:
arr = np.arange(10)

In [63]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr[5]

5

In [65]:
arr[5:8]

array([5, 6, 7])

In [66]:
arr[5:8] = 12

In [67]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## Create an array from an array slice

In [68]:
arr_slice = arr[5:8]

In [69]:
arr_slice

array([12, 12, 12])

## Changes to the sliced array show up in the original array

In [70]:
arr_slice[1] = 12345

In [71]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [72]:
arr_slice[:] = 64

In [73]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

## Individual elements in multidimensional array are indexed like one-dimensional arrays

In [74]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [75]:
arr2d[2]

array([7, 8, 9])

In [76]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
old_value = arr3d[0].copy()

In [80]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [81]:
arr3d[1, 0]

array([7, 8, 9])

In [82]:
x = arr3d[1]

In [83]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [84]:
x[0]

array([7, 8, 9])

## Indexing with slices

In [85]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [86]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [87]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [90]:
lower_dim_slice = arr2d[1, :2]

In [91]:
arr2d[:2, 2]

array([3, 6])

## Using slicing to replace values in array

In [92]:
arr2d[:2, 1:] = 0

In [93]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [94]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [95]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
   .....:                  [-12, -4], [3, 4]])


In [96]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [97]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

## Looking for a value in the array

In [98]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

## If arrays are of equal length, the variable passed will return the indexes that match its location in the original array

In [99]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [100]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [101]:
data[names == "Bob", 1]

array([7, 0])

In [102]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [103]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [104]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [105]:
mask = (names == "Bob") | (names == "Will")

In [106]:
mask

array([ True, False,  True,  True,  True, False, False])

In [107]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [108]:
data[data < 0] = 0

In [109]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [110]:
data[names != "Joe"] = 7

In [111]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [112]:
arr = np.zeros((8, 4))

In [113]:
for i in range(8):
    arr[i] = i

In [114]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [115]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [116]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

## Selecting multiple index arrays selects a one-dimensional array of elements corresponding to each tuple of indices

In [117]:
arr = np.arange(32).reshape((8, 4))

In [118]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [119]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]


array([ 4, 23, 29, 10])

In [120]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [121]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [122]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [123]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

## Transposing Arrays and Swapping Axes

In [124]:
arr = np.arange(15).reshape((3, 5))

In [125]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [126]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [127]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1
]])


In [128]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [129]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [130]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [131]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

## takes a pair of axis numbers and switches the indicated axes to rearrange the data

In [132]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

## Pseudorandom Number Generation

In [133]:
samples = np.random.standard_normal(size=(4, 4))

In [134]:
samples

array([[-0.26198679,  0.63537237,  1.06191453,  1.57676716],
       [-0.34413085,  0.77165457,  0.62554099,  0.64654283],
       [ 0.31564045, -0.11559293,  1.47343389,  0.50472618],
       [ 1.77622143,  0.04808053, -0.71660379, -0.19229174]])

In [135]:
from random import normalvariate

In [136]:
N = 1000000

In [137]:
timeit samples = [normalvariate(0, 1) for _ in range(N)]

539 ms ± 4.75 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [138]:
timeit np.random.standard_normal(N)

33.1 ms ± 443 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [139]:
type(rng)

NameError: name 'rng' is not defined

# output should be numpy.random._generator.Generator

## Universal Functions: Fast Element-Wise Array Functions

In [ ]:
arr = np.arange(10)

In [ ]:
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
x = rng.standard_normal(8)

In [ ]:
y = rng.standard_normal(8)

In [ ]:
x

In [ ]:
y

In [ ]:
np.maximum(x, y)

# output should be array([-0.467 ,  0.6489,  0.7888, -1.2567,  2.3474,  1.399 ,  1.3223,
#        0.9022])

In [ ]:
# arr = rng.standard_normal(7) * 5

# arr
# array([ 4.5146, -8.1079, -0.7909,  2.2474, -6.718 , -0.4084,  8.6237])

# remainder, whole_part = np.modf(arr)

# remainder
# array([ 0.5146, -0.1079, -0.7909,  0.2474, -0.718 , -0.4084,  0.6237])

# whole_part
# array([ 4., -8., -0.,  2., -6., -0.,  8.])

In [ ]:
# arr
# array([ 4.5146, -8.1079, -0.7909,  2.2474, -6.718 , -0.4084,  8.6237])

# out = np.zeros_like(arr)

# np.add(arr, 1)
# array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

# np.add(arr, 1, out=out)
# array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

# out
# array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

In [143]:
# Array-Oriented Programming with Arrays