In [19]:
import numpy as np

In [20]:
# 4 NumPy Basics: Arrays and Vectorized Computation

In [21]:
# declare a numpy array and a python list from 0 to 999,999

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [22]:
# compare the performance of each
# numpy arrays are generally 10 to 100 times faster than their python list counterparts

%timeit myarr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

776 µs ± 19.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
23.5 ms ± 577 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# ndarray (N-dimensional array object): A Multidimensional Array Object

In [23]:
# declare an array made up of two python lists

data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [24]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [25]:
# numpy allows you to perform computations against whole blocks of code

data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [26]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [27]:
# Every array has a shape, a tuple indicating the size of each dimension, in this case 2 rows, 3 columns

data.shape

(2, 3)

In [28]:
data.dtype

dtype('float64')

## Creating arrays using the array function

In [29]:
# This accepts any sequence-like object (including other arrays) and produces a new NumPy array 
# containing the passed data

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [30]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [31]:
# Nested sequences will be converted into a multidimensional array

In [32]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [33]:
arr2 = np.array(data2)

In [34]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
# returns the number of dimensions (axis) in the array

arr2.ndim

2

In [36]:
arr2.shape

(2, 4)

In [37]:
# np.array tries to infer a good data type for the array it creates

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr2.dtype

dtype('int64')

In [40]:
# create an array of 0s using np.zeroes

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [43]:
# create an array of 1s using np.ones

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
# create an empty array using np.empty. It’s not safe to assume that numpy.empty will return an array of all zeros. This function returns uninitialized memory and thus may contain nonzero "garbage" values. You should use this function only if you intend to 
# populate the new array with data.

In [47]:
np.empty((1, 2, 3))

array([[[ 3. , -0.2,  6. ],
        [ 0. , -6. , 13. ]]])

In [48]:
# create an array using arange(n) from 0 to n-1
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data types for ndarrays (datatype:bitsperelement)

In [49]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [50]:
arr1.dtype

dtype('float64')

In [51]:
arr2.dtype

dtype('int32')

In [52]:
arr = np.array([1, 2, 3, 4, 5]) 

In [53]:
arr.dtype

dtype('int64')

In [54]:
float_arr = arr.astype(np.float64)

In [55]:
float_arr

array([1., 2., 3., 4., 5.])

In [56]:
float_arr.dtype

dtype('float64')

In [57]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [58]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [59]:
# You can explicitly convert or cast an array from one data type to another using ndarray’s astype method
# Calling astype always creates a new array (a copy of the data), 
# even if the new data type is the same as the old data type.

In [60]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [61]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [62]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

# Using Another Array'ss dtype to Change Array dtype

In [63]:
int_array = np.arange(10)

In [64]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [65]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [66]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [67]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## Arithmetic with Numpy Arrays

In [68]:
arr = np.array([[1., 2., 3.], [4., 5., 6]])

In [69]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [70]:
# Elements in the array will have arithmetic performed with the element at the matching index

In [71]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [72]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
1 - arr

array([[ 0., -1., -2.],
       [-3., -4., -5.]])

In [74]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [75]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [76]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [77]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [78]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [79]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

# Basic Indexing and Slicing

In [80]:
# One-dimensional arrays are simple; on the surface they act similarly to Python lists

In [81]:
arr = np.arange(10)

In [82]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
arr[5]

5

In [84]:
arr[5:8]

array([5, 6, 7])

In [85]:
arr[5:8] = 12

In [86]:
# As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, 
# the value is propagated (or broadcast henceforth) to the entire selection.

In [87]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [88]:
# An important first distinction from Python's built-in lists is that 
# array slices are views on the original array. This means that the 
# data is not copied, and any modifications to the view will be reflected in the source array.

## Create an array from an array slice

In [89]:
# Create an array populated by the values at the sliced indexes

In [90]:
arr_slice = arr[5:8]

In [91]:
arr_slice

array([12, 12, 12])

## Changes to the sliced array show up in the original array

In [92]:
arr_slice[1] = 12345

In [93]:
# Here arr_slice[1] correlates to the 7th index in the original array because it is made from the [5:8] slice

In [94]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [95]:
# The bare slice will assign to all values in an array. Again, arr_slice is created from arr[5:8]
# so it will overwrite the values at those indexes.
# If you want a copy of a slice of an ndarray instead of a view, you will need to 
# explicitly copy the array—for example, arr[5:8].copy()

In [96]:
arr_slice[:] = 64

In [97]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [98]:
# Individual elements in multidimensional array are indexed like one-dimensional arrays

In [99]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [100]:
arr2d[2]

array([7, 8, 9])

In [101]:
# In a two-dimensional array, the elements at each index are no 
# longer scalars but rather one-dimensional arrays
# array[index of element in array, index of value in element]

In [102]:
arr2d[0,2]

3

In [103]:
arr2d[2,1]

8

In [104]:
# arr3d is an array with 2 lists at each index

In [105]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [106]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [107]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [109]:
old_value = arr3d[0].copy()

In [110]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [111]:
# Since arr3d is an array made up of lists of lists, the slice [1, 0] 
# first references the element at index 1 [[7, 8, 9], [10, 11, 12]] and then the element at the 0 index within
# that element [7, 8, 9]

In [112]:
arr3d[1, 0]

array([7, 8, 9])

In [113]:
x = arr3d[1]

In [114]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [115]:
x[0]

array([7, 8, 9])

## Indexing with slices

In [116]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [117]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [118]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
# Slicing for the first 2 elements in the array which are lists [1, 2, 3] and [4, 5, 6]

In [120]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
# Select the first 2 rows from arr2d, and from those rows
# give me the values from the the second column to the end

In [122]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [123]:
# Select the first row in the array, and give me the value from the first 2 columns 

In [124]:
lower_dim_slice = arr2d[1, :2]

In [125]:
# should return (2,)

In [126]:
arr2d[:2, 2]

array([3, 6])

## Using slicing to replace values in array

In [127]:
# In the first 2 rows, in the first 2 columns replace all values with 0

In [128]:
arr2d[:2, 1:] = 0

In [129]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [130]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [131]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
   .....:                  [-12, -4], [3, 4]])


In [132]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [133]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [134]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [135]:
# If arrays are of equal length, the variable passed will return the indexes 
# that match its location in the original array

In [136]:
# Bob can be found at indexes 0 and 3 which is where [4, 7] and [0, 0] are in their array

In [137]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [138]:
# ???

In [139]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [140]:
# ??? 

In [141]:
data[names == "Bob", 1]

array([7, 0])

In [142]:
# The ~ operator can be useful when you want to invert a Boolean array referenced by a variable

In [143]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [144]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [145]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [146]:
# mask is used to call the array and return True for all indexes that contain Bob or Will

In [147]:
mask = (names == "Bob") | (names == "Will")

In [148]:
mask

array([ True, False,  True,  True,  True, False, False])

In [149]:
# Passing mask to the data array to see what indexes correspond to the indexes that contain Bob or Will

In [150]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [151]:
# Selecting data from an array by Boolean indexing and assigning 
# the result to a new variable always creates a copy of the data, even if the returned array is unchanged.

In [152]:
# Setting all negative values in the array to 0

In [153]:
data[data < 0] = 0

In [154]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [155]:
# You can also set whole rows or columns using a one-dimensional Boolean array

In [156]:
data[names != "Joe"] = 7

In [157]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

# Fancy Indexing

In [158]:
# Create an array of zeroes that is 8 rows by 4 columns

In [159]:
arr = np.zeros((8, 4))

In [160]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [161]:
# Creating an array in the range of 0 to n - 1

In [162]:
for i in range(8):
    arr[i] = i

In [163]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [164]:
# To select a subset of the rows in a particular order, you can simply pass a 
# list or ndarray of integers specifying the desired order

In [165]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [166]:
# Using negative indices selects rows from the end

In [167]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [168]:
# Selecting multiple index arrays selects a one-dimensional array 
# of elements corresponding to each tuple of indices

In [169]:
# you can convert an array from one shape to another without copying any data. 
# To do this, pass a tuple indicating the new shape to the reshape array instance method

In [170]:
arr = np.arange(32).reshape((8, 4))

In [171]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [172]:
# ???

In [173]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [174]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [175]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [176]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [177]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

## Transposing Arrays and Swapping Axes

In [178]:
arr = np.arange(15).reshape((3, 5))

In [179]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [180]:
# Using the T attribute to swap axes (3 x 5 -> 5 x 3)

In [181]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [182]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1
]])


In [183]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [184]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [185]:
# The @ infix operator is another way to do matrix multiplication

In [186]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [187]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [188]:
# ndarray has the method swapaxes, which takes a pair of axis numbers and switches 
# the indicated axes to rearrange the data
# swapaxes similarly returns a view on the data without making a copy.

In [189]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

## Pseudorandom Number Generation

In [190]:
samples = np.random.standard_normal(size=(4, 4))

In [191]:
samples

array([[-1.04556165,  1.67821017, -0.13120607,  1.08050261],
       [ 0.09647376,  0.10625236, -0.6509877 ,  1.86669587],
       [ 1.17592764,  0.83185196, -0.82095887, -0.63631785],
       [-0.14091805, -1.06460841, -0.33829726,  3.12184897]])

In [192]:
from random import normalvariate

In [193]:
N = 1000000

In [194]:
timeit samples = [normalvariate(0, 1) for _ in range(N)]

285 ms ± 3.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [195]:
timeit np.random.standard_normal(N)

15 ms ± 153 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [196]:
data = rng.standard_normal((2, 3))

NameError: name 'rng' is not defined

In [ ]:
type(rng)

In [ ]:
# output should be numpy.random._generator.Generator

## Universal Functions: Fast Element-Wise Array Functions

In [ ]:
arr = np.arange(10)

In [ ]:
arr

In [ ]:
# get the square root of each value in the array

In [ ]:
np.sqrt(arr)

In [ ]:
# get the exponential value of each value in the array

In [ ]:
np.exp(arr)

In [ ]:
x = rng.standard_normal(8)

In [ ]:
y = rng.standard_normal(8)

In [ ]:
x

In [ ]:
# should output:
# array([-1.3678,  0.6489,  0.3611, -1.9529,  2.3474,  0.9685, -0.7594,
#         0.9022])

In [ ]:
y

In [ ]:
# should output:
# array([-0.467 , -0.0607,  0.7888, -1.2567,  0.5759,  1.399 ,  1.3223,
#        -0.2997])

In [ ]:
# numpy.maximum computes the element-wise maximum of the elements in x and y.

In [ ]:
np.maximum(x, y)

In [ ]:
# should output:
# array([-0.467 ,  0.6489,  0.7888, -1.2567,  2.3474,  1.399 ,  1.3223,
#         0.9022])

In [ ]:
arr = rng.standard_normal(7) * 5

In [ ]:
arr

In [ ]:
# should output: 
# array([ 4.5146, -8.1079, -0.7909,  2.2474, -6.718 , -0.4084,  8.6237])

In [ ]:
# math.modf, it returns the fractional and integral parts of a floating-point array:

In [ ]:
remainder, whole_part = np.modf(arr)

In [ ]:
remainder

In [ ]:
# should return array([ 0.5146, -0.1079, -0.7909,  0.2474, -0.718 , -0.4084,  0.6237])

In [ ]:
whole_part

In [ ]:
# should return array([ 4., -8., -0.,  2., -6., -0.,  8.]) 

In [ ]:
arr

In [ ]:
# should return array([ 4.5146, -8.1079, -0.7909,  2.2474, -6.718 , -0.4084,  8.6237])

In [ ]:
out = np.zeros_like(arr)

In [ ]:
np.add(arr, 1)

In [ ]:
# should return array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

In [ ]:
# out argument that allows them to assign their results into an existing array rather than create a new one

In [ ]:
np.add(arr, 1, out=out)

In [ ]:
# should return array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

In [ ]:
out

In [ ]:
# should return array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

# Array-Oriented Programming with Arrays

In [ ]:
# The numpy.meshgrid function takes two one-dimensional arrays 
# and produces two two-dimensional matrices corresponding to all pairs of (x, y) in the two arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 100 equally spaced points

In [ ]:
xs, ys = np.meshgrid(points, points)

In [ ]:
ys

In [ ]:
xs

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [ ]:
z

In [ ]:
import matplotlib.pyplot as plt 

In [ ]:
plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])

In [ ]:
# should return <matplotlib.image.AxesImage at 0x7fb10d993640>

In [ ]:
plt.colorbar()

In [ ]:
# should return <matplotlib.colorbar.Colorbar at 0x7fb10a93d610>

In [ ]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
# Text(0.5, 1.0, 'Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

In [ ]:
# If you're working in IPython, you can close all open plot windows by executing plt.close("all")

# Expressing Conditional Logic as Array Operations

In [198]:
# The numpy.where function is a vectorized version of the ternary expression x if condition else y

In [199]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

In [200]:
result = [(x if c else y)
.....:           for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [201]:
result = np.where(cond, xarr, yarr)

In [202]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [203]:
arr = rng.standard_normal((4, 4))

NameError: name 'rng' is not defined

In [204]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
# should return array([[ 2.6182,  0.7774,  0.8286, -0.959 ],
#        [-1.2094, -1.4123,  0.5415,  0.7519],
#        [-0.6588, -1.2287,  0.2576,  0.3129],
#        [-0.1308,  1.27  , -0.093 , -0.0662]])

In [205]:
arr > 0

array([[False,  True, False],
       [ True,  True, False],
       [ True,  True,  True],
       [False, False, False],
       [ True, False,  True]])

In [ ]:
# should return array([[ True,  True,  True, False],
#        [False, False,  True,  True],
#        [False, False,  True,  True],
#        [False,  True, False, False]])

In [206]:
np.where(arr > 0, 2, -2)

array([[-2,  2, -2],
       [ 2,  2, -2],
       [ 2,  2,  2],
       [-2, -2, -2],
       [ 2, -2,  2]])

In [207]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 0,  2,  0],
       [ 2,  2, -2],
       [ 2,  2,  2],
       [-1,  0, -1],
       [ 2,  0,  2]])

In [ ]:
# array([[ 2.    ,  2.    ,  2.    , -0.959 ],
#        [-1.2094, -1.4123,  2.    ,  2.    ],
#       [-0.6588, -1.2287,  2.    ,  2.    ],
#       [-0.1308,  2.    , -0.093 , -0.0662]])

# Mathematical and Statistical Methods

In [208]:
arr = rng.standard_normal((5, 4))

NameError: name 'rng' is not defined

In [209]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
# should return array([[-1.1082,  0.136 ,  1.3471,  0.0611],
#        [ 0.0709,  0.4337,  0.2775,  0.5303],
#       [ 0.5367,  0.6184, -0.795 ,  0.3   ],
#       [-1.6027,  0.2668, -1.2616, -0.0713],
#       [ 0.474 , -0.4149,  0.0977, -1.6404]])

In [210]:
arr.mean()

0.8666666666666667

In [ ]:
# should return -0.08719744457434529

In [211]:
np.mean(arr)

0.8666666666666667

In [ ]:
# should return -0.08719744457434529

In [213]:
arr.sum()

13

In [ ]:
# should return -1.743948891486906

In [214]:
arr.mean(axis=1) # arr.mean(axis=1) means "compute mean across the columns"

array([ 0.33333333,  0.33333333,  3.66666667, -0.66666667,  0.66666667])

In [ ]:
# should return array([ 0.109 ,  0.3281,  0.165 , -0.6672, -0.3709])

In [215]:
arr.sum(axis=0) # arr.sum(axis=0) means "compute sum down the rows."

array([7, 6, 0])

In [ ]:
# should return array([-1.6292,  1.0399, -0.3344, -0.8203])

In [ ]:
# Other methods like cumsum and cumprod do not aggregate, instead producing an array of the intermediate results

In [ ]:
In [199]: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [200]: arr.cumsum()
Out[200]: array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [ ]:
# In multidimensional arrays, accumulation functions like cumsum return an 
# array of the same size but with the partial aggregates computed along the 
# indicated axis according to each lower dimensional slice

In [ ]:
In [201]: arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [202]: arr
Out[202]: 
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# The expression arr.cumsum(axis=0) computes the cumulative sum along the rows, 
# while arr.cumsum(axis=1) computes the sums along the columns

In [ ]:
In [203]: arr.cumsum(axis=0)
Out[203]: 
array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [204]: arr.cumsum(axis=1)
Out[204]: 
array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

# Methods for Boolean Arrays

In [ ]:
In [205]: arr = rng.standard_normal(100)

In [206]: (arr > 0).sum() # Number of positive values
Out[206]: 48

In [207]: (arr <= 0).sum() # Number of non-positive values
Out[207]: 52

In [ ]:
# The parentheses here in the expression (arr > 0).sum() are necessary to be 
# able to call sum() on the temporary result of arr > 0.
# Two additional methods, any and all, are useful especially for Boolean arrays. 
# any tests whether one or more values in an array is True, while all checks if every value is True

In [ ]:
In [208]: bools = np.array([False, False, True, False])

In [209]: bools.any()
Out[209]: True

In [210]: bools.all()
Out[210]: False

# Sorting

In [ ]:
# Like Python’s built-in list type, NumPy arrays can be sorted in place with the sort method

In [ ]:
In [211]: arr = rng.standard_normal(6)

In [212]: arr
Out[212]: array([ 0.0773, -0.6839, -0.7208,  1.1206, -0.0548, -0.0824])

In [213]: arr.sort()

In [214]: arr
Out[214]: array([-0.7208, -0.6839, -0.0824, -0.0548,  0.0773,  1.1206])

In [ ]:
In [215]: arr = rng.standard_normal((5, 3))

In [216]: arr
Out[216]: 
array([[ 0.936 ,  1.2385,  1.2728],
       [ 0.4059, -0.0503,  0.2893],
       [ 0.1793,  1.3975,  0.292 ],
       [ 0.6384, -0.0279,  1.3711],
       [-2.0528,  0.3805,  0.7554]])

In [ ]:
# arr.sort(axis=0) sorts the values within each column, while arr.sort(axis=1) sorts across each row

In [ ]:
In [217]: arr.sort(axis=0)

In [218]: arr
Out[218]: 
array([[-2.0528, -0.0503,  0.2893],
       [ 0.1793, -0.0279,  0.292 ],
       [ 0.4059,  0.3805,  0.7554],
       [ 0.6384,  1.2385,  1.2728],
       [ 0.936 ,  1.3975,  1.3711]])

In [219]: arr.sort(axis=1)

In [220]: arr
Out[220]: 
array([[-2.0528, -0.0503,  0.2893],
       [-0.0279,  0.1793,  0.292 ],
       [ 0.3805,  0.4059,  0.7554],
       [ 0.6384,  1.2385,  1.2728],
       [ 0.936 ,  1.3711,  1.3975]])

In [ ]:
# The top-level method numpy.sort returns a sorted copy of an array 
# (like the Python built-in function sorted) instead of modifying the array in place

In [ ]:
In [221]: arr2 = np.array([5, -10, 7, 1, 0, -3])

In [222]: sorted_arr2 = np.sort(arr2)

In [223]: sorted_arr2
Out[223]: array([-10,  -3,   0,   1,   5,   7])

# Unique and Other Set Logic

In [ ]:
# numpy.unique, which returns the sorted unique values in an array

In [ ]:
In [224]: names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])

In [225]: np.unique(names)
Out[225]: array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [226]: ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [227]: np.unique(ints)
Out[227]: array([1, 2, 3, 4])

In [ ]:
# Contrast numpy.unique with the pure Python alternative

In [ ]:
In [228]: sorted(set(names))
Out[228]: ['Bob', 'Joe', 'Will']

# File Input and Output with Arrays

In [ ]:
# numpy.save and numpy.load are the two workhorse functions for 
# efficiently saving and loading array data on disk. Arrays are saved by 
# default in an uncompressed raw binary format with file extension .npy

In [ ]:
In [231]: arr = np.arange(10)

In [232]: np.save("some_array", arr)

In [ ]:
# If the file path does not already end in .npy, the extension will be appended. 
# The array on disk can then be loaded with numpy.load

In [ ]:
In [233]: np.load("some_array.npy")
Out[233]: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# You can save multiple arrays in an uncompressed archive using numpy.savez 
# and passing the arrays as keyword arguments:

In [ ]:
In [234]: np.savez("array_archive.npz", a=arr, b=arr)

In [ ]:
# When loading an .npz file, you get back a dictionary-like object that loads the individual arrays lazily

In [ ]:
In [235]: arch = np.load("array_archive.npz")

In [236]: arch["b"]
Out[236]: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# If your data compresses well, you may wish to use numpy.savez_compressed instead

In [ ]:
In [237]: np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

# Linear Algebra

In [ ]:
# Multiplying two two-dimensional arrays with * is an element-wise product, 
# while matrix multiplications require either using the dot function or the @ infix operator. 
# dot is both an array method and a function in the numpy namespace for doing matrix multiplication

In [ ]:
In [241]: x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [242]: y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [243]: x
Out[243]: 
array([[1., 2., 3.],
       [4., 5., 6.]])

In [244]: y
Out[244]: 
array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [245]: x.dot(y)
Out[245]: 
array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
x.dot(y) is equivalent to np.dot(x, y)

In [ ]:
In [246]: np.dot(x, y)
Out[246]: 
array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
# A matrix product between a two-dimensional array and a suitably sized 
# one-dimensional array results in a one-dimensional array

In [ ]:
In [247]: x @ np.ones(3)
Out[247]: array([ 6., 15.])

In [ ]:
# numpy.linalg has a standard set of matrix decompositions and things like inverse and determinant

In [ ]:
In [248]: from numpy.linalg import inv, qr

In [249]: X = rng.standard_normal((5, 5))

In [250]: mat = X.T @ X

In [251]: inv(mat)
Out[251]: 
array([[  3.4993,   2.8444,   3.5956, -16.5538,   4.4733],
       [  2.8444,   2.5667,   2.9002, -13.5774,   3.7678],
       [  3.5956,   2.9002,   4.4823, -18.3453,   4.7066],
       [-16.5538, -13.5774, -18.3453,  84.0102, -22.0484],
       [  4.4733,   3.7678,   4.7066, -22.0484,   6.0525]])

In [252]: mat @ inv(mat)
Out[252]: 
array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [-0.,  0.,  0.,  0.,  1.]])

In [ ]:
# The expression X.T.dot(X) computes the dot product of X with its transpose X.T

# Random Walks

In [ ]:
# Here is a pure Python way to implement a single random walk with 1,000 steps using the built-in random module

In [ ]:
#! blockstart
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
#! blockend

In [ ]:
# an example plot of the first 100 values on one of these random walks

In [ ]:
plt.plot(walk[:100])

In [ ]:
# walk is the cumulative sum of the random steps and could be evaluated as an array expression

In [ ]:
In [256]: nsteps = 1000

In [257]: rng = np.random.default_rng(seed=12345)  # fresh random generator

In [258]: draws = rng.integers(0, 2, size=nsteps)

In [259]: steps = np.where(draws == 0, 1, -1)

In [260]: walk = steps.cumsum()

In [ ]:
# From this we can begin to extract statistics like the minimum and maximum value along the walk’s trajectory

In [ ]:
In [261]: walk.min()
Out[261]: -8

In [262]: walk.max()
Out[262]: 50

In [ ]:
# argmax, which returns the first index of the maximum value in the Boolean array (True is the maximum value)

In [ ]:
In [263]: (np.abs(walk) >= 10).argmax()
Out[263]: 155

In [217]:
# Simulating Many Random Walks at Once

In [ ]:
In [264]: nwalks = 5000

In [265]: nsteps = 1000

In [266]: draws = rng.integers(0, 2, size=(nwalks, nsteps)) # 0 or 1

In [267]: steps = np.where(draws > 0, 1, -1)

In [268]: walks = steps.cumsum(axis=1)

In [269]: walks
Out[269]: 
array([[  1,   2,   3, ...,  22,  23,  22],
       [  1,   0,  -1, ..., -50, -49, -48],
       [  1,   2,   3, ...,  50,  49,  48],
       ...,
       [ -1,  -2,  -1, ..., -10,  -9, -10],
       [ -1,  -2,  -3, ...,   8,   9,   8],
       [ -1,   0,   1, ...,  -4,  -3,  -2]])

In [ ]:
# Now, we can compute the maximum and minimum values obtained over all of the walks

In [ ]:
In [270]: walks.max()
Out[270]: 114

In [271]: walks.min()
Out[271]: -120

In [ ]:
# Out of these walks, let’s compute the minimum crossing time to 30 or –30 using the any method

In [ ]:
In [272]: hits30 = (np.abs(walks) >= 30).any(axis=1)

In [273]: hits30
Out[273]: array([False,  True,  True, ...,  True, False,  True])

In [274]: hits30.sum() # Number that hit 30 or -30
Out[274]: 3395

In [ ]:
# We can use this Boolean array to select the rows of walks that actually 
# cross the absolute 30 level, and call argmax across axis 1 to get the crossing times

In [ ]:
In [275]: crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)

In [276]: crossing_times
Out[276]: array([201, 491, 283, ..., 219, 259, 541])

In [ ]:
# Lastly, we compute the average minimum crossing time

In [ ]:
In [277]: crossing_times.mean()
Out[277]: 500.5699558173785