In [233]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [234]:
# declare a numpy array and a python list from 0 to 999,999

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [235]:
# compare the performance of each
# numpy arrays are generally 10 to 100 times faster than their python list counterparts

%timeit myarr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

673 µs ± 47.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
22.7 ms ± 772 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## The NumPy ndarray - allows you to run mathematical calculations on a block of data

In [230]:
# declare an array made up of two python lists

data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [231]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [232]:
# numpy allows you to perform computations against whole blocks of code

data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [236]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [98]:
data.shape

(2, 3)

In [99]:
data.dtype

dtype('float64')

## Creating arrays using the array function

In [100]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [101]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

## Nested sequences will be converted into a multidimensional array

In [102]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [103]:
arr2 = np.array(data2)

In [104]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
arr2.ndim

2

In [106]:
arr2.shape

(2, 4)

## np.array tries to infer a good data type for the array it creates

In [107]:
arr1.dtype

dtype('float64')

In [108]:
arr2.dtype

dtype('int64')

## create an array of 0s or 1s using .zeroes or .ones

In [109]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [111]:
np.empty((2, 3, 2))

array([[[0.00000000e+000, 1.00937611e-320],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.16095484e-028]],

       [[5.45772260e+222, 1.46899930e+179],
        [9.08367237e+223, 1.16466228e-028],
        [3.99914468e+252, 1.46030983e-319]]])

In [112]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data types for ndarrays

## dtype is a special object containing the metadata about the array 

In [113]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [114]:
arr1.dtype

dtype('float64')

In [115]:
arr2.dtype

dtype('int32')

In [116]:
arr = np.array([1, 2, 3, 4, 5]) 

In [117]:
arr.dtype

dtype('int64')

In [118]:
float_arr = arr.astype(np.float64)

In [119]:
float_arr

array([1., 2., 3., 4., 5.])

In [120]:
float_arr.dtype

dtype('float64')

In [121]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [122]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [123]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [124]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [125]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## using another arrays dtype to change array dtype

In [126]:
int_array = np.arange(10)

In [127]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [128]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [129]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [130]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## Arithmetic with Numpy Arrays

In [131]:
arr = np.array([[1., 2., 3.], [4., 5., 6]])

In [132]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [133]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [134]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [135]:
1 - arr

array([[ 0., -1., -2.],
       [-3., -4., -5.]])

In [136]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [137]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [138]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [139]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [140]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [141]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [142]:
## Basic Indexing and Slicing

In [143]:
arr = np.arange(10)

In [144]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
arr[5]

5

In [146]:
arr[5:8]

array([5, 6, 7])

In [147]:
arr[5:8] = 12

In [148]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## Create an array from an array slice

In [149]:
arr_slice = arr[5:8]

In [150]:
arr_slice

array([12, 12, 12])

## Changes to the sliced array show up in the original array

In [151]:
arr_slice[1] = 12345

In [152]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [153]:
arr_slice[:] = 64

In [154]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

## Individual elements in multidimensional array are indexed like one-dimensional arrays

In [155]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [156]:
arr2d[2]

array([7, 8, 9])

In [157]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [158]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [159]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
old_value = arr3d[0].copy()

In [161]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [162]:
arr3d[1, 0]

array([7, 8, 9])

In [163]:
x = arr3d[1]

In [164]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [165]:
x[0]

array([7, 8, 9])

## Indexing with slices

In [166]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [167]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [168]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [172]:
lower_dim_slice = arr2d[1, :2]

In [173]:
arr2d[:2, 2]

array([3, 6])

## Using slicing to replace values in array

In [174]:
arr2d[:2, 1:] = 0

In [175]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [176]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [177]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
   .....:                  [-12, -4], [3, 4]])


In [178]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [179]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

## Looking for a value in the array

In [180]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

## If arrays are of equal length, the variable passed will return the indexes that match its location in the original array

In [181]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [182]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [183]:
data[names == "Bob", 1]

array([7, 0])

In [184]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [185]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [186]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [187]:
mask = (names == "Bob") | (names == "Will")

In [188]:
mask

array([ True, False,  True,  True,  True, False, False])

In [189]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [190]:
data[data < 0] = 0

In [191]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [192]:
data[names != "Joe"] = 7

In [193]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [194]:
arr = np.zeros((8, 4))

In [195]:
for i in range(8):
    arr[i] = i

In [196]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [197]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [198]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

## Selecting multiple index arrays selects a one-dimensional array of elements corresponding to each tuple of indices

In [199]:
arr = np.arange(32).reshape((8, 4))

In [200]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [201]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]


array([ 4, 23, 29, 10])

In [202]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [203]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [204]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [205]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

## Transposing Arrays and Swapping Axes

In [206]:
arr = np.arange(15).reshape((3, 5))

In [207]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [208]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [209]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1
]])


In [210]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [211]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [212]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [213]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

## takes a pair of axis numbers and switches the indicated axes to rearrange the data

In [214]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

## Pseudorandom Number Generation

In [215]:
samples = np.random.standard_normal(size=(4, 4))

In [216]:
samples

array([[-0.08649048, -0.02965351, -0.75828512,  0.30235794],
       [-1.38740269, -1.84968685,  1.15235627,  0.29642377],
       [ 0.93399157,  1.46197198, -2.71185609, -1.45681213],
       [-0.17666687,  1.48426161, -1.29761059, -1.14887143]])

In [217]:
from random import normalvariate

In [218]:
N = 1000000

In [219]:
timeit samples = [normalvariate(0, 1) for _ in range(N)]

272 ms ± 2.11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [220]:
timeit np.random.standard_normal(N)

14.8 ms ± 199 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [221]:
type(rng)

NameError: name 'rng' is not defined

# output should be numpy.random._generator.Generator

## Universal Functions: Fast Element-Wise Array Functions

In [ ]:
arr = np.arange(10)

In [ ]:
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
x = rng.standard_normal(8)

In [ ]:
y = rng.standard_normal(8)

In [ ]:
x

In [ ]:
y

In [ ]:
np.maximum(x, y)

# output should be array([-0.467 ,  0.6489,  0.7888, -1.2567,  2.3474,  1.399 ,  1.3223,
#        0.9022])

In [222]:
arr = rng.standard_normal(7) * 5

arr
# array([ 4.5146, -8.1079, -0.7909,  2.2474, -6.718 , -0.4084,  8.6237])

# remainder, whole_part = np.modf(arr)

# remainder
# array([ 0.5146, -0.1079, -0.7909,  0.2474, -0.718 , -0.4084,  0.6237])

# whole_part
# array([ 4., -8., -0.,  2., -6., -0.,  8.])

NameError: name 'rng' is not defined

In [ ]:
# arr
# array([ 4.5146, -8.1079, -0.7909,  2.2474, -6.718 , -0.4084,  8.6237])

# out = np.zeros_like(arr)

# np.add(arr, 1)
# array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

# np.add(arr, 1, out=out)
# array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

# out
# array([ 5.5146, -7.1079,  0.2091,  3.2474, -5.718 ,  0.5916,  9.6237])

In [ ]:
# Array-Oriented Programming with Arrays