In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

## The NumPy ndarray - allows you to run mathematical calculations on a block of data

In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [4]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

In [8]:
## Creating arrays using the array function

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
## Nested sequences will be converted into a multidimensional array

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [13]:
arr2 = np.array(data2)

In [14]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

In [17]:
## np.array tries to infer a good data type for the array it creates

In [18]:
arr1.dtype

dtype('float64')

In [19]:
arr2.dtype

dtype('int64')

In [20]:
## create an array of 0s or 1s using .zeroes or .ones

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.empty((2, 3, 2))

array([[[1.28822975e-231, 1.73060500e-077],
        [3.95252517e-323, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
## Data types for ndarrays

In [26]:
## dtype is a special object containing the metadata about the array 

In [27]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
arr = np.array([1, 2, 3, 4, 5]) 

In [31]:
arr.dtype

dtype('int64')

In [32]:
float_arr = arr.astype(np.float64)

In [33]:
float_arr

array([1., 2., 3., 4., 5.])

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [38]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [39]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [40]:
## using another arrays dtype to change array dtype

In [41]:
int_array = np.arange(10)

In [42]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [43]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [45]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [46]:
## Arithmetic with Numpy Arrays

In [47]:
arr = np.array([[1., 2., 3.], [4., 5., 6]])

In [48]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
1 - arr

array([[ 0., -1., -2.],
       [-3., -4., -5.]])

In [52]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [53]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [54]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [55]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [56]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [57]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [58]:
## Basic Indexing and Slicing

In [59]:
arr = np.arange(10)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr[5]

5

In [62]:
arr[5:8]

array([5, 6, 7])

In [63]:
arr[5:8] = 12

In [64]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [65]:
## Create an array from an array slice

In [66]:
arr_slice = arr[5:8]

In [67]:
arr_slice

array([12, 12, 12])

In [68]:
## Changes to the sliced array show up in the original array

In [69]:
arr_slice[1] = 12345

In [70]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [71]:
arr_slice[:] = 64

In [72]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [73]:
## Individual elements in multidimensional array are indexed like one-dimensional arrays

In [74]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [75]:
arr2d[2]

array([7, 8, 9])

In [76]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [87]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
old_value = arr3d[0].copy()

In [89]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
arr3d[1, 0]

array([7, 8, 9])

In [91]:
x = arr3d[1]

In [92]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [93]:
x[0]

array([7, 8, 9])

In [94]:
## Indexing with slices

In [95]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [96]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [97]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [103]:
lower_dim_slice = arr2d[1, :2]

In [104]:
arr2d[:2, 2]

array([3, 6])

In [109]:
## Using slicing to replace values in array

In [110]:
arr2d[:2, 1:] = 0

In [111]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [112]:
## Boolean Indexing

In [115]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [116]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
   .....:                  [-12, -4], [3, 4]])


In [118]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [119]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
## Looking for a value in the array

In [120]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

## If arrays are of equal length, the variable passed will return the indexes that match its location in the original array

In [122]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [124]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [125]:
data[names == "Bob", 1]

array([7, 0])

In [127]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [129]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [130]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [131]:
mask = (names == "Bob") | (names == "Will")

In [132]:
mask

array([ True, False,  True,  True,  True, False, False])

In [133]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [134]:
data[data < 0] = 0

In [135]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [136]:
data[names != "Joe"] = 7

In [137]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [138]:
arr = np.zeros((8, 4))

In [139]:
for i in range(8):
    arr[i] = i

In [140]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [141]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [142]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [143]:
## Selecting multiple index arrays selects a one-dimensional array of elements corresponding to each tuple of indices

In [144]:
arr = np.arange(32).reshape((8, 4))

In [145]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [146]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]


array([ 4, 23, 29, 10])

In [ ]:
arr[[1, 5, 7, 3]][:0, 3, 1, 2]]